import { StyleSheet } from 'react-native';
import { Colors } from '../../colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  headerIconButton: {
    padding: 6,
  },
  headerTitleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: Colors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  headerDoneButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: Colors.primaryLight,
  },
  headerDoneText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  body: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  sectionTitle: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  sectionEmpty: {
    color: Colors.textSecondary,
    fontStyle: 'italic',
    fontSize: 12,
    marginBottom: 8,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  itemInput: {
    flex: 1,
    backgroundColor: Colors.card,
    color: Colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    fontSize: 14,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  statusToggleGroup: {
    flexDirection: 'row',
    gap: 4,
  },
  statusButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderDark,
    backgroundColor: 'transparent',
  },
  statusButtonOkActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  statusButtonSkipActive: {
    backgroundColor: Colors.danger,
    borderColor: Colors.danger,
  },
  statusButtonText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: Colors.textSecondary,
  },
  statusButtonTextOkActive: {
    color: Colors.background,
  },
  statusButtonTextSkipActive: {
    color: Colors.text,
  },
  itemRemove: {
    padding: 6,
  },
  achievementCard: {
    marginTop: 8,
    marginBottom: 16,
    padding: 12,
    borderRadius: 8,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  achievementCardComplete: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryLight,
  },
  achievementTitle: {
    color: Colors.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  achievementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  achievementRate: {
    color: Colors.primary,
    fontSize: 24,
    fontWeight: 'bold',
  },
  achievementProgress: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
  achievementDetail: {
    color: Colors.textSecondary,
    fontSize: 12,
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.primary,
    borderStyle: 'dashed',
    alignSelf: 'flex-start',
  },
  addItemText: {
    color: Colors.primary,
    fontWeight: '600',
    fontSize: 13,
  },
  memoInput: {
    backgroundColor: Colors.card,
    color: Colors.text,
    padding: 12,
    borderRadius: 8,
    minHeight: 80,
    fontSize: 14,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  resetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 32,
    marginBottom: 24,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: Colors.dangerLight,
    borderWidth: 1,
    borderColor: Colors.dangerMedium,
  },
  resetButtonText: {
    color: Colors.danger,
    fontWeight: '600',
    fontSize: 13,
  },
});
