import { StyleSheet } from 'react-native';
import { Colors } from '../colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    backgroundColor: '#121212',
  },
  headerTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 10,
  },
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    padding: 8,
  },
  content: {
    flex: 1,
  },
  exerciseList: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  exerciseCard: {
    backgroundColor: '#1E1E1E',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
  },
  exerciseInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12, // 세트 리스트와 간격
  },
  exerciseIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  exerciseText: {
    flex: 1,
  },
  exerciseName: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  exerciseMeta: {
    color: Colors.primary,
    fontSize: 10,
    marginTop: 2,
  },
  setRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  setIndexBox: {
    width: 30,
    alignItems: 'center',
  },
  setIndexText: {
    color: '#888',
    fontSize: 12,
    fontWeight: 'bold',
  },
  setValueBox: {
    flex: 1,
    alignItems: 'center',
  },
  setValueText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  setValueLabel: {
    color: Colors.primary,
    fontSize: 10,
    marginLeft: 4,
  },
  memoSection: {
    padding: 16,
    backgroundColor: '#1E1E1E',
    marginTop: 16,
    marginBottom: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
  },
  memoTitle: {
    color: '#888',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  memoText: {
    color: 'white',
    fontSize: 14,
    lineHeight: 20,
  },
  memoInput: {
    color: 'white',
    fontSize: 14,
    lineHeight: 20,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  // Editing Styles
  saveButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.primaryLight,
    borderRadius: 16,
  },
  saveButtonText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  section: {
    padding: 16,
  },
  label: {
    color: '#888',
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#1E1E1E',
    color: 'white',
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
  },
  divider: {
    height: 1,
    backgroundColor: '#333',
    marginVertical: 8,
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: Colors.overlayLight,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  exerciseTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  reorderHandle: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#1f1f1f',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  exerciseDeleteButton: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: Colors.dangerLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseNameInput: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    padding: 0,
  },
  setsContainer: {
    padding: 12,
  },
  setHeaderRow: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  setHeaderText: {
    color: Colors.primary,
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  setNumber: {
    color: '#888',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  setInput: {
    backgroundColor: '#2C2C2C',
    color: 'white',
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
    textAlign: 'center',
    fontWeight: '600',
    height: 40,
  },
  emptyStateButton: {
    padding: 32,
    borderWidth: 2,
    borderColor: Colors.primary,
    borderStyle: 'dashed',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  emptyStateText: {
    color: Colors.primary,
    fontSize: 16,
  },
  fabContainer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  fab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 30,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  fabText: {
    color: '#121212',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  setControlContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    backgroundColor: '#2C2C2C',
    borderRadius: 6,
    padding: 2,
    height: 40,
  },
  setControlButton: {
    width: 32,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#383838',
    borderRadius: 4,
  },
  setCountText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteActionButton: {
    marginRight: 8,
  },
  keyboardAvoiding: {
    flex: 1,
  },
  reorderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  moveButton: {
    padding: 8,
  },
  confirmButton: {
    padding: 6,
    backgroundColor: Colors.primary,
    borderRadius: 4,
    marginLeft: 4,
  },
  headerSpacer: {
    width: 30,
  },
  setIndexContainer: {
    width: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  setInputLayout: {
    flex: 1,
    marginLeft: 8,
  },
  removeSetButton: {
    width: 30,
    alignItems: 'flex-end',
  },
  footerSpacer: {
    height: 100,
  },
  setHeaderTextFixed: {
    width: 100,
  },
  setHeaderTextFlex: {
    flex: 1,
  },
});
