import { StyleSheet } from 'react-native';
import { Colors } from '../colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingBottom: 0,
    marginBottom: 20,
    backgroundColor: '#121212',
  },
  headerTitle: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  iconButton: {
    padding: 8,
  },
  saveButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.primaryLight,
    borderRadius: 16,
  },
  saveButtonText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
  },
  section: {
    padding: 16,
  },
  label: {
    color: '#888',
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#1E1E1E',
    color: 'white',
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
  },
  deleteButton: {
    backgroundColor: Colors.dangerLight,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderWidth: 1,
    borderColor: Colors.dangerMedium,
  },
  deleteButtonText: {
    color: '#ff4444',
    fontWeight: 'bold',
    fontSize: 14,
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 8,
  },
  tag: {
    backgroundColor: Colors.primaryMedium,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.primaryBorder,
  },
  tagText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  addTagButton: {
    width: 32,
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#666',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: '#333',
    marginVertical: 8,
  },
  exerciseCard: {
    position: 'relative', // Ensure zIndex works correctly
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    marginBottom: 16,
    // overflow: 'hidden', // Removed to allow dropdown to overflow
    borderWidth: 1,
    borderColor: 'transparent',
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: Colors.overlayLight,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  exerciseTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  reorderHandle: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#1f1f1f',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  exerciseDeleteButton: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: Colors.dangerLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseInfo: {
    marginLeft: 12,
    flex: 1,
  },
  exerciseNameInput: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    padding: 0,
  },
  setsContainer: {
    padding: 12,
  },
  setHeaderRow: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  setHeaderText: {
    color: '#666',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  setRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  setNumber: {
    color: '#888',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  syncButton: {
    marginLeft: 4,
    padding: 4,
  },
  setInput: {
    backgroundColor: '#2C2C2C',
    color: 'white',
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
    textAlign: 'center',
    fontWeight: '600',
    height: 40,
  },
  emptyStateButton: {
    padding: 32,
    borderWidth: 2,
    borderColor: '#333',
    borderStyle: 'dashed',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  emptyStateText: {
    color: '#666',
    fontSize: 16,
  },
  fabContainer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  fab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 30,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  fabText: {
    color: '#121212',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  // Set Control Styles
  setControlContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    backgroundColor: '#2C2C2C',
    borderRadius: 6,
    padding: 2,
    height: 40,
  },
  setControlButton: {
    width: 32,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#383838',
    borderRadius: 4,
  },
  setCountText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  reorderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  moveButton: {
    padding: 8,
  },
  confirmButton: {
    padding: 6,
    backgroundColor: Colors.primary,
    borderRadius: 4,
    marginLeft: 4,
  },
  setIndexContainer: {
    width: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  setInputLayout: {
    flex: 1,
    marginLeft: 8,
  },
  removeSetButton: {
    width: 30,
    alignItems: 'flex-end',
  },
  footerSpacer: {
    height: 100,
  },
  setHeaderTextFixed: {
    width: 100,
  },
  setHeaderTextFlex: {
    flex: 1,
  },
  headerSpacer: {
    width: 30,
  },
  keyboardAvoiding: {
    flex: 1,
  },
});
